services:
  backend:
    image: job-tracker-backend
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - PORT=${PORT:-8080}
      - APP_ENV=${APP_ENV:-production}
      - BLUEPRINT_DB_URL=/app/db/jobs.db
    volumes:
      - sqlite_data:/app/db
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: job-tracker-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80" # Map Nginx port to host port 80
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlite_data:
    name: jobs.db

networks:
  default:
    name: jobtracker-network
